apiVersion: networking.k8s.io/v1  # API 버전
kind: Ingress  # Kubernetes 리소스 타입
metadata:
  name: common-ingress-apigw  # Ingress의 이름
  namespace: backend  # Ingress가 속한 네임스페이스
  annotations:
    # Let's Encrypt 발급자를 지정하는 인증서 관리자 관련 설정
    cert-manager.io/issuer: "letsencrypt-production"
    # SSL 리다이렉션을 활성화하여 HTTP 요청을 HTTPS로 리다이렉션함
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # CORS(Cross-Origin Resource Sharing)를 활성화함
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # 허용하는 HTTP 메소드를 설정함
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    # 모든 오리진에서의 요청을 허용함
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    # CORS 요청에서 허용하는 헤더를 설정함
    nginx.ingress.kubernetes.io/cors-allow-headers: "authorization, origin, content-type, accept"
    # CORS 사전 요청의 최대 나이(초)를 설정함
    nginx.ingress.kubernetes.io/cors-max-age: "3600"
spec:
  ingressClassName: nginx  # 사용할 Ingress 컨트롤러의 클래스 이름
  rules:
    - host: moamoa-backend.duckdns.org  # 요청을 처리할 호스트 이름
      http:
        paths:
        - path: /  # 요청을 처리할 경로
          pathType: Prefix  # 경로 타입 설정, Prefix는 지정된 경로로 시작하는 모든 요청을 포함
          backend:
            service:
              name: kong-proxy-external  # 요청을 전달할 서비스 이름(Kong API Gateway)
              port:
                number: 80  # 서비스의 포트 번호
  defaultBackend:
    service:
      name: kong-proxy-external
      port:
        number: 80
  tls:
  - hosts:
    - moamoa-backend.duckdns.org  # TLS를 적용할 호스트 이름
    secretName: moa-backend-tls  # TLS 인증서를 포함하는 시크릿의 이름
