apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  version: 8.10.4
  nodeSets:
  - name: masters
    count: 1
    config:
      # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
      # node.master: true
      node.roles: ["master"]
      # xpack.ml.enabled: true
      # node.remote_cluster_client: false
      node.store.allow_mmap: false
  - name: data
    count: 2
    config:
      # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
      # node.master: false
      # node.data: true
      # node.ingest: true
      # node.ml: true
      # node.transform: true
      node.roles: ["data", "ingest"]
      # node.remote_cluster_client: false
      node.store.allow_mmap: false



      
