apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: elk
spec:
  type: filebeat
  version: 8.10.4
  config:
    logging.level: debug
    filebeat:
      autodiscover:
        providers:
        - node: ${NODE_NAME}
          type: kubernetes
          hints:
            enabled: true
            default_config:
              type: container
              paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
    output.logstash:
      hosts: ["logstash-ls-beats.elk.svc.cluster.local:5044"]
      ssl_enabled: true
      ssl:
        certificate_authorities:
        - /usr/share/filebeat/config/certs/tls.crt
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: elasticsearch-certs
            mountPath: /usr/share/filebeat/config/certs
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumes:
        - name: elasticsearch-certs
          secret:
            secretName: elasticsearch-es-http-certs-public
