apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: kafka-logstash
  namespace: elk
spec:
  count: 1
  version: 8.8.0
  elasticsearchRefs:
    - clusterName: eck
      name: elasticsearch
  pipelines:
    - pipeline.id: kafka
      config.string: |
        input {
          kafka {
            bootstrap_servers => "kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
            topics => ["search"]
            group_id => "search"
            consumer_threads => 3
            
          }
        }
        output {
          stdout {
              codec => rubydebug
          }    
          elasticsearch {
              hosts => [ "${ECK_ES_HOSTS}" ]
              user => "awdfaf"
              password => "awdfaf"
              ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
              index => "search"
            }
        }

