apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: kafka-logstash
  namespace: elk
spec:
  count: 1
  version: 8.8.0
  elasticsearchRefs:
    - clusterName: eck
      name: elasticsearch
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          kafka {
            bootstrap_servers => "kafka-0.kafka.svc.cluster.local:9092"
            topics => ["local-test"]
            group_id => "yourGroupId"
            consumer_threads => 3
            codec => json
          }
        }
        output {
        
          elasticsearch {
            hosts => [ "${ECK_ES_HOSTS}" ]
            user => "${ECK_ES_USER}"
            password => "${ECK_ES_PASSWORD}"
            ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
            index => "yourIndexName"
          }
        }

