apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elk
spec:
  version: 8.8.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elk
  config:
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-monitoring.elk.svc.cluster.local:9200"]
    xpack.monitoring.ui.ccs.enabled: true
