apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: elk
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      clusterName: elk
  version: 8.10.4
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "${ES_HOSTS}" ]
            user => "${ES_USER}"
            password => "${ES_PASSWORD}"
            ssl_certificate_authorities => "/usr/share/logstash/config/certs/ca.crt"
            ssl => true
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
  podTemplate:
    spec:
      containers:
        - name: logstash
          volumeMounts:
            - name: elasticsearch-certs
              mountPath: /usr/share/logstash/config/certs
          env:
            - name: ES_USER
              value: "elastic"
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
            - name: ES_HOSTS
              value: "https://elasticsearch-es-http.elk.svc:9200"
      volumes:
        - name: elasticsearch-certs
          secret:
            secretName: elasticsearch-es-http-certs-public
